name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            node-modules: true
        - uses: actions/setup-node@v1
          with:
            node-version: 16
        - name: Install WebdriverIO
          run: npm install
        - name: Run Tests
          run: npm run wdio